### ISSUE TITLE
register_buffer

### ISSUE THREAD

**Issue by Forbu** [loudinthecloud/pytorch-ntm#1]
I have an issue regarding the training, I launch the program I get :

```KeyError: "attribute 'mem_bias' already exists"```

It seems that you define 2 times mem_bias in memory.py :

```
self.mem_bias = Variable(torch.Tensor(N, M))
self.register_buffer('mem_bias', self.mem_bias.data)
```

It is perhaps a problem with the pytorch version (I have pytorch 0.3).

**Comment by loudinthecloud** [comment]
Hi @Forbu , thanks for reporting 👍
