### ISSUE TITLE
Strange fluctuation on curves even after large #seqs have been trained with

### ISSUE THREAD

**Issue by marcwww** [loudinthecloud/pytorch-ntm#10]
![7711528080263_ pic_hd](https://user-images.githubusercontent.com/10141302/40896139-f8b9ed32-67e5-11e8-8af6-ae35532355b1.jpg)
![7701528080263_ pic_hd](https://user-images.githubusercontent.com/10141302/40896140-f8f45346-67e5-11e8-8507-2878f9a6d96f.jpg)

(random seed=10)
As the plots show, after 120,000 seqs, there still occurs some fluctuation of cost, which seems not to match that of the results in your experiments and the original authors'. 
What could probably be the reasons?
How to copy with this?
THANKS A LOT.

**Comment by loudinthecloud** [comment]
Hey, can you please test after reverting d7b38405753e99fab6435cc4075e46607c75013d?

**Comment by marcwww** [comment]
![image](https://user-images.githubusercontent.com/10141302/41011977-0e392c08-6972-11e8-8cdc-8767213909f3.png)
![image](https://user-images.githubusercontent.com/10141302/41011983-1402338c-6972-11e8-86c3-deb29f70c329.png)
it seems that change does not helpy

**Comment by loudinthecloud** [comment]
Interesting, perhaps it's related to the seed (initialization and random training samples). Can you please test using a different seed? My test involved averaging 4 different seeds. I'll try to reproduce with seed=10 as well.

**Comment by loudinthecloud** [comment]
It's seems to be a seed issue, I attached plots for the training of the copy task with seed=1000. Results may vary based on the seed as it controls the initialization and the training examples as well (which are random sequences of bits).

![Loss](https://user-images.githubusercontent.com/3178431/41902213-91f4495a-793b-11e8-9da6-b606db9b89a7.png)

![Cost](https://user-images.githubusercontent.com/3178431/41902238-9f06d982-793b-11e8-92ee-5c7378721abf.png)

**Comment by marcwww** [comment]
Could u please list a detailed param setting? Thanks a lot.

**Comment by loudinthecloud** [comment]
Hi, sure. 
It appears in the copy notebook, at the beginning.
