### ISSUE TITLE
How to change code when each sequence length is different

### ISSUE THREAD

**Issue by REDXXXX** [loudinthecloud/pytorch-ntm#17]
Dear sir:
    Sorry for my rude words.But I do really want to know how to change the code if the sequence length is different.It seems that ntm need sequence length to be the same.
    I tried to fill short sequence with zero but the ntm use attention  and if filled with zero the predict rate down.
    I want to know how could I do to overcome the problem.Please help me.
    Best wishes to you.

**Comment by loudinthecloud** [comment]
The sequence length doesn't have to be the same, you can end each sequence with a special delimiter. The input sequence length is also randomized between 10 to 20 in the copy task and you can even see an example of variable length **output** in the repeat-copy task where the NTM learns to output a sequence multiple times and end it with a delimiter.
