### ISSUE TITLE
How could u write down beta, gamma in your source code?

### ISSUE THREAD

**Issue by dragen1860** [loudinthecloud/pytorch-ntm#7]
![image](https://user-images.githubusercontent.com/4252555/40348350-0fcf51de-5dd6-11e8-999d-1017e79f69af.png)

Hi, I found your code has the latin characters $\beta$, $\gamma$. It's wired and interesting for me. Could you explain how to achieve this?

**Comment by loudinthecloud** [comment]
Sure, I inserted unicode characters instead of letters or words, it looked more clean and elegant at the time.
On Linux, use ctrl + shift + u followed by hex code.
